version: '3.3'

services:
  weatherforecast:
    container_name: weatherforecast
    hostname: weatherforecast
    image: weatherforecast
    restart: on-failure
    build: .
    ports:
      - 80:8080
      - 443:8443
    expose:
      - '8080' 
      - '8443'
    networks:
      - backend
networks:
  backend:
    driver: bridge